/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    Breadcrumb: typeof import('./src/components/Layout/Breadcrumb.vue')['default']
    ConfigValidator: typeof import('./src/components/ConfigValidator.vue')['default']
    ConfigWizard: typeof import('./src/components/ConfigWizard.vue')['default']
    DataSourceStatus: typeof import('./src/components/Sync/DataSourceStatus.vue')['default']
    DeepModelSelector: typeof import('./src/components/DeepModelSelector.vue')['default']
    DevPanel: typeof import('./src/components/Dev/DevPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    GlobalConfirm: typeof import('./src/components/Global/GlobalConfirm.vue')['default']
    GlobalNotification: typeof import('./src/components/Global/GlobalNotification.vue')['default']
    HeaderActions: typeof import('./src/components/Layout/HeaderActions.vue')['default']
    MarketSelector: typeof import('./src/components/Global/MarketSelector.vue')['default']
    ModelConfig: typeof import('./src/components/ModelConfig.vue')['default']
    MultiMarketStockSearch: typeof import('./src/components/Global/MultiMarketStockSearch.vue')['default']
    MultiSourceSyncCard: typeof import('./src/components/Dashboard/MultiSourceSyncCard.vue')['default']
    NetworkStatus: typeof import('./src/components/NetworkStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/Layout/SidebarMenu.vue')['default']
    SyncControl: typeof import('./src/components/Sync/SyncControl.vue')['default']
    SyncHistory: typeof import('./src/components/Sync/SyncHistory.vue')['default']
    SyncRecommendations: typeof import('./src/components/Sync/SyncRecommendations.vue')['default']
    TaskReportDialog: typeof import('./src/components/Global/TaskReportDialog.vue')['default']
    TaskResultDialog: typeof import('./src/components/Global/TaskResultDialog.vue')['default']
    UserProfile: typeof import('./src/components/Layout/UserProfile.vue')['default']
  }
}
